/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package group.project.recycling;

/**
 *
 * @author zoheb
 */
public class DepotCardsGUI extends javax.swing.JPanel {

    /**
     * Creates new form DepotCardsGUI
     */
    public DepotCardsGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLbl = new javax.swing.JLabel();
        locationLbl = new javax.swing.JLabel();
        openTimeLbl = new javax.swing.JLabel();
        pNumLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(215, 215, 215));

        nameLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameLbl.setText("Name");

        locationLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        locationLbl.setText("Location");

        openTimeLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        openTimeLbl.setText("Open - Close time");

        pNumLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pNumLbl.setText("Phone number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(pNumLbl)
                    .addComponent(openTimeLbl)
                    .addComponent(locationLbl)
                    .addComponent(nameLbl))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(nameLbl)
                .addGap(18, 18, 18)
                .addComponent(locationLbl)
                .addGap(18, 18, 18)
                .addComponent(openTimeLbl)
                .addGap(18, 18, 18)
                .addComponent(pNumLbl)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel locationLbl;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel openTimeLbl;
    private javax.swing.JLabel pNumLbl;
    // End of variables declaration//GEN-END:variables
}
