/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package group.project.recycling;

/**
 *
 * @author zoheb
 */
public class DepotCardGUI extends javax.swing.JPanel {

    /**
     * Creates new form DepotCardsGUI
     */
    public DepotCardGUI() {
        initComponents();
    }

    public void setStreetLbl(String street) {
        streetLbl.setText(street);
    }

    public void setCityLbl(String city) {
        cityLbl.setText(city);
    }

    public void setNameLbl(String name) {
        nameLbl.setText(name);
    }

    public void setTimeLbl(String openTime, String closeTime) {
        openTimeLbl.setText(openTime + " - " + closeTime);
    }

    public void setPhoneNumLbl(String num) {
        pNumLbl.setText(num);
    }

    public void setReadError(String text) {
        fileReadErrLbl.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLbl = new javax.swing.JLabel();
        streetLbl = new javax.swing.JLabel();
        openTimeLbl = new javax.swing.JLabel();
        pNumLbl = new javax.swing.JLabel();
        fileReadErrLbl = new javax.swing.JLabel();
        cityLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(215, 215, 215));

        nameLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        nameLbl.setText("Name");

        streetLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        streetLbl.setText("Location");

        openTimeLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        openTimeLbl.setText("Open - Close time");

        pNumLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        pNumLbl.setText("Phone number");

        fileReadErrLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N

        cityLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        cityLbl.setText("City");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(pNumLbl)
                    .addComponent(openTimeLbl)
                    .addComponent(streetLbl)
                    .addComponent(nameLbl)
                    .addComponent(fileReadErrLbl)
                    .addComponent(cityLbl))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(nameLbl)
                .addGap(18, 18, 18)
                .addComponent(streetLbl)
                .addGap(18, 18, 18)
                .addComponent(cityLbl)
                .addGap(13, 13, 13)
                .addComponent(openTimeLbl)
                .addGap(18, 18, 18)
                .addComponent(pNumLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileReadErrLbl)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cityLbl;
    private javax.swing.JLabel fileReadErrLbl;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel openTimeLbl;
    private javax.swing.JLabel pNumLbl;
    private javax.swing.JLabel streetLbl;
    // End of variables declaration//GEN-END:variables
}
