/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package group.project.recycling;

import java.util.List;

/**
 *
 * @author zoheb
 */
public class FacilityCardGUI extends javax.swing.JPanel {

    /**
     * Creates new form FacilityCard
     */
    public FacilityCardGUI() {
        initComponents();
    }

    public void setNameLbl(String name) {
        nameLbl.setText(formatText(name));
    }

    public void setStreetLbl(String street) {
        streetLbl.setText(formatText(street));
    }

    public void setCityLbl(String city) {
        cityLbl.setText(formatText(city));
    }

    public void setCountyLbl(String county) {
        countyLbl.setText(formatText(county));
    }
    
    public void setTimeLbl(String openTime, String closeTime){
        openTimeLbl.setText(openTime + " - " + closeTime);
    }
    
    public void setAcceptedWasteLbl(List<String> items){
        String itemString = String.join(", ", items);
        wasteTxtAr.setText(itemString);
    }
    
    public void setEmailLbl(String email){
        emailLbl.setText(email);
    }
    
    public void setNumLbl(String num){
        pNumLbl.setText(num);
    }
    
    public void setImgIconPath(String path){
        try {
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource(path)).getImage().getScaledInstance(256, 256, java.awt.Image.SCALE_SMOOTH));
            imgLbl.setIcon(icon);
        } catch(Exception e) {
            System.out.println("Err loading img");
        } 
    }
    
    private String formatText(String text){
        String firstLetter = text.substring(0, 1); // Extracts text from 0 to 1
        
        if(!text.isBlank()){
            // Extract text from 1 onwards and concatinate to first letter
            return firstLetter.toUpperCase() + text.substring(1);
        } 
        
        return text;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        streetLbl = new javax.swing.JLabel();
        openTimeLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        pNumLbl = new javax.swing.JLabel();
        cityLbl = new javax.swing.JLabel();
        countyLbl = new javax.swing.JLabel();
        wasteTxtAr = new javax.swing.JTextArea();

        imgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/group/project/recycling/img/placeholder.png"))); // NOI18N

        nameLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        nameLbl.setText("Name");

        streetLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        streetLbl.setText("Street");

        openTimeLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        openTimeLbl.setText("Open time - Close time");

        emailLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        emailLbl.setText("Email");

        pNumLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        pNumLbl.setText("Phone nunber");

        cityLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        cityLbl.setText("City");

        countyLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        countyLbl.setText("County");

        wasteTxtAr.setEditable(false);
        wasteTxtAr.setColumns(20);
        wasteTxtAr.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        wasteTxtAr.setLineWrap(true);
        wasteTxtAr.setRows(5);
        wasteTxtAr.setText("Waste Accepted");
        wasteTxtAr.setWrapStyleWord(true);
        wasteTxtAr.setAutoscrolls(false);
        wasteTxtAr.setBorder(null);
        wasteTxtAr.setCaretColor(new java.awt.Color(242, 242, 242));
        wasteTxtAr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        wasteTxtAr.setFocusable(false);
        wasteTxtAr.setMargin(new java.awt.Insets(0, 0, 0, 0));
        wasteTxtAr.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wasteTxtAr)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLbl)
                            .addComponent(openTimeLbl)
                            .addComponent(streetLbl)
                            .addComponent(cityLbl)
                            .addComponent(countyLbl)
                            .addComponent(emailLbl)
                            .addComponent(pNumLbl))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(streetLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cityLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(countyLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(openTimeLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pNumLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wasteTxtAr, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imgLbl))
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cityLbl;
    private javax.swing.JLabel countyLbl;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JLabel imgLbl;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel openTimeLbl;
    private javax.swing.JLabel pNumLbl;
    private javax.swing.JLabel streetLbl;
    private javax.swing.JTextArea wasteTxtAr;
    // End of variables declaration//GEN-END:variables
}
