/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package group.project.recycling;

/**
 *
 * @author zoheb
 */
public class FacilityCardGUI extends javax.swing.JPanel {

    /**
     * Creates new form FacilityCard
     */
    public FacilityCardGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        locationLbl = new javax.swing.JLabel();
        openTimeLbl = new javax.swing.JLabel();
        wasteAcceptedLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        pNumLbl = new javax.swing.JLabel();

        imgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/group/project/recycling/img/placeholder.png"))); // NOI18N

        nameLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        nameLbl.setText("Name");

        locationLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        locationLbl.setText("Location");

        openTimeLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        openTimeLbl.setText("Open time - Close time");

        wasteAcceptedLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        wasteAcceptedLbl.setText("Waste Accepted");

        emailLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        emailLbl.setText("Email");

        pNumLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        pNumLbl.setText("Phone nunber");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLbl)
                    .addComponent(openTimeLbl)
                    .addComponent(locationLbl)
                    .addComponent(wasteAcceptedLbl)
                    .addComponent(emailLbl)
                    .addComponent(pNumLbl))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgLbl)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(nameLbl)
                        .addGap(18, 18, 18)
                        .addComponent(locationLbl)
                        .addGap(18, 18, 18)
                        .addComponent(openTimeLbl)
                        .addGap(18, 18, 18)
                        .addComponent(wasteAcceptedLbl)
                        .addGap(18, 18, 18)
                        .addComponent(emailLbl)
                        .addGap(18, 18, 18)
                        .addComponent(pNumLbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailLbl;
    private javax.swing.JLabel imgLbl;
    private javax.swing.JLabel locationLbl;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel openTimeLbl;
    private javax.swing.JLabel pNumLbl;
    private javax.swing.JLabel wasteAcceptedLbl;
    // End of variables declaration//GEN-END:variables
}
