/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group.project.recycling;

/**
 *
 * @author zoheb
 */
public class RecyclingFrame extends javax.swing.JFrame {
    private DepotsGUI depots;
    private BrowseFacilitiesGUI browse;
    private AddFacilityGUI facilities;

    /**
     * Creates new form RecyclingFrame
     */
    public RecyclingFrame() {
        initComponents();
        
        //set layout
        setLayout(new java.awt.FlowLayout());
        
        // add depots section
        depots = new DepotsGUI();
        add(depots);
        
        // add browse facilities section
        browse = new BrowseFacilitiesGUI();
        add(browse);
        browse.setVisible(false);
        
        // add add facility section
        facilities = new AddFacilityGUI();
        add(facilities);
        facilities.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navPanel = new javax.swing.JPanel();
        depotsBtn = new javax.swing.JButton();
        browseFacBtn = new javax.swing.JButton();
        addFacBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1110, 764));
        setMinimumSize(new java.awt.Dimension(1110, 764));
        setPreferredSize(new java.awt.Dimension(1110, 764));
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        depotsBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        depotsBtn.setText("Our Depots");
        depotsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depotsBtnActionPerformed(evt);
            }
        });

        browseFacBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        browseFacBtn.setText("Browse Facilities");
        browseFacBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseFacBtnActionPerformed(evt);
            }
        });

        addFacBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        addFacBtn.setText("Add Your Facility");
        addFacBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFacBtnActionPerformed(evt);
            }
        });

        homeBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navPanelLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navPanelLayout);
        navPanelLayout.setHorizontalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(homeBtn)
                .addGap(40, 40, 40)
                .addComponent(depotsBtn)
                .addGap(30, 30, 30)
                .addComponent(browseFacBtn)
                .addGap(34, 34, 34)
                .addComponent(addFacBtn)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        navPanelLayout.setVerticalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(homeBtn)
                    .addComponent(depotsBtn)
                    .addComponent(browseFacBtn)
                    .addComponent(addFacBtn))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(navPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeBtnActionPerformed

    private void depotsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depotsBtnActionPerformed
        // TODO add your handling code here:
        setPanelVisible(depots, depots, browse, facilities);
    }//GEN-LAST:event_depotsBtnActionPerformed

    private void browseFacBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseFacBtnActionPerformed
        // TODO add your handling code here:
        setPanelVisible(browse, depots, browse, facilities);
    }//GEN-LAST:event_browseFacBtnActionPerformed

    private void addFacBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFacBtnActionPerformed
        // TODO add your handling code here:
        setPanelVisible(facilities, depots, browse, facilities);
    }//GEN-LAST:event_addFacBtnActionPerformed

    static void setPanelVisible(javax.swing.JPanel panel, DepotsGUI depots, BrowseFacilitiesGUI browse, AddFacilityGUI facilities){
        depots.setVisible(panel == depots);
        browse.setVisible(panel == browse);
        facilities.setVisible(panel == facilities);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecyclingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecyclingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecyclingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecyclingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecyclingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFacBtn;
    private javax.swing.JButton browseFacBtn;
    private javax.swing.JButton depotsBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JPanel navPanel;
    // End of variables declaration//GEN-END:variables
}
