/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group.project.recycling;

/**
 *
 * @author zoheb
 */
public class RecyclingFrameGUI extends javax.swing.JFrame {
    private DepotsSectionGUI depotsGUI;
    private BrowseFacilitiesSectionGUI browseGUI;
    private AddFacilitySectionGUI facilitiesGUI;

    /**
     * Creates new form RecyclingFrame
     * @param depotsGUI
     * @param browseGUI
     * @param facilitiesGUI
     */
    public RecyclingFrameGUI(DepotsSectionGUI depotsGUI,BrowseFacilitiesSectionGUI browseGUI,AddFacilitySectionGUI facilitiesGUI) {
        initComponents();
        
        //set layout
        setLayout(new java.awt.FlowLayout());
        
        // Store GUI
        this.depotsGUI = depotsGUI;
        this.browseGUI = browseGUI;
        this.facilitiesGUI = facilitiesGUI;
        
        // Add GUI panels to frame
        add(this.depotsGUI);
        add(this.browseGUI);
        add(this.facilitiesGUI);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navPanel = new javax.swing.JPanel();
        depotsBtn = new javax.swing.JButton();
        browseFacBtn = new javax.swing.JButton();
        addFacBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1110, 764));
        setMinimumSize(new java.awt.Dimension(1110, 764));
        setPreferredSize(new java.awt.Dimension(1110, 764));
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        depotsBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        depotsBtn.setText("Our Depots");
        depotsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depotsBtnActionPerformed(evt);
            }
        });

        browseFacBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        browseFacBtn.setText("Browse Facilities");
        browseFacBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseFacBtnActionPerformed(evt);
            }
        });

        addFacBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        addFacBtn.setText("Add Your Facility");
        addFacBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFacBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navPanelLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navPanelLayout);
        navPanelLayout.setHorizontalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(depotsBtn)
                .addGap(30, 30, 30)
                .addComponent(browseFacBtn)
                .addGap(34, 34, 34)
                .addComponent(addFacBtn)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        navPanelLayout.setVerticalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(depotsBtn)
                    .addComponent(browseFacBtn)
                    .addComponent(addFacBtn))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(navPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depotsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depotsBtnActionPerformed
        // TODO add your handling code here:
        setPanelVisible(depotsGUI);
    }//GEN-LAST:event_depotsBtnActionPerformed

    private void browseFacBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseFacBtnActionPerformed
        // TODO add your handling code here:
        setPanelVisible(browseGUI);
    }//GEN-LAST:event_browseFacBtnActionPerformed

    private void addFacBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFacBtnActionPerformed
        // TODO add your handling code here:
        setPanelVisible(facilitiesGUI);
    }//GEN-LAST:event_addFacBtnActionPerformed

    private void setPanelVisible(javax.swing.JPanel panel){
        depotsGUI.setVisible(panel == depotsGUI);
        browseGUI.setVisible(panel == browseGUI);
        facilitiesGUI.setVisible(panel == facilitiesGUI);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecyclingFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecyclingFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecyclingFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecyclingFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RecyclingFrameGUI().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFacBtn;
    private javax.swing.JButton browseFacBtn;
    private javax.swing.JButton depotsBtn;
    private javax.swing.JPanel navPanel;
    // End of variables declaration//GEN-END:variables
}
