/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group.project;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Matty School
 */
public class FeedbackGUI extends javax.swing.JFrame {

    /**
     * Creates new form TechGUI
     */
    public FeedbackGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        question1Lbl = new javax.swing.JLabel();
        question1Cbx = new javax.swing.JComboBox<>();
        question2Lbl = new javax.swing.JLabel();
        rdB1 = new javax.swing.JRadioButton();
        rdB2 = new javax.swing.JRadioButton();
        question3Lbl = new javax.swing.JLabel();
        rdB3 = new javax.swing.JRadioButton();
        rdB4 = new javax.swing.JRadioButton();
        rdB5 = new javax.swing.JRadioButton();
        question4Lbl = new javax.swing.JLabel();
        rdB6 = new javax.swing.JRadioButton();
        rdB7 = new javax.swing.JRadioButton();
        rdB8 = new javax.swing.JRadioButton();
        submitBtn = new javax.swing.JButton();
        question5Lbl = new javax.swing.JLabel();
        question5Cbx = new javax.swing.JComboBox<>();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        title.setText("FeedBack");

        question1Lbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        question1Lbl.setText("Q1. Would you consider buying used items over new items ?  ");

        question1Cbx.setFont(new java.awt.Font("Eras Medium ITC", 0, 10)); // NOI18N
        question1Cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Choose", "Yes", "No" }));

        question2Lbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        question2Lbl.setText("Q2. What kind of waste in the world do you think impacts us most ?  ");

        buttonGroup1.add(rdB1);
        rdB1.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        rdB1.setText("Improper Diposal of waste products ");
        rdB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdB1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdB2);
        rdB2.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        rdB2.setText("The impacts of Fast Fashion ");

        question3Lbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        question3Lbl.setText("Q3. Are you aware of the effects of fast fashion ? ");

        buttonGroup2.add(rdB3);
        rdB3.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        rdB3.setText("Not Aware ");

        buttonGroup2.add(rdB4);
        rdB4.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        rdB4.setText("Somewhat Aware ");

        buttonGroup2.add(rdB5);
        rdB5.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        rdB5.setText("Very Aware");
        rdB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdB5ActionPerformed(evt);
            }
        });

        question4Lbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        question4Lbl.setText("Q4. Are you aware of how your waste is disposed of ? ");

        buttonGroup3.add(rdB6);
        rdB6.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        rdB6.setText("No clue");

        buttonGroup3.add(rdB7);
        rdB7.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        rdB7.setText("Some Idea");

        buttonGroup3.add(rdB8);
        rdB8.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        rdB8.setText("Completely Aware");

        submitBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        submitBtn.setText("Submit Results");

        question5Lbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        question5Lbl.setText("Q5. Has viewing our site made you more conscious of how you will re use items going forward ");

        question5Cbx.setFont(new java.awt.Font("Eras Medium ITC", 0, 10)); // NOI18N
        question5Cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Choose", "Yes", "No" }));

        backBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(question2Lbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question4Lbl)
                            .addComponent(question3Lbl))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rdB3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdB4)
                        .addGap(99, 99, 99)
                        .addComponent(rdB5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdB6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdB1)
                                .addGap(49, 49, 49)
                                .addComponent(rdB2)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rdB7)
                        .addGap(101, 101, 101)
                        .addComponent(rdB8)
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question5Lbl)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(question1Lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(question1Cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 52, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(submitBtn)
                        .addGap(48, 48, 48)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(question5Cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(question1Cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(question1Lbl))
                        .addGap(30, 30, 30)
                        .addComponent(question2Lbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdB2)
                            .addComponent(rdB1))))
                .addGap(30, 30, 30)
                .addComponent(question3Lbl)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdB4)
                    .addComponent(rdB3)
                    .addComponent(rdB5))
                .addGap(27, 27, 27)
                .addComponent(question4Lbl)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdB7)
                    .addComponent(rdB8)
                    .addComponent(rdB6))
                .addGap(35, 35, 35)
                .addComponent(question5Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(question5Cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitBtn)
                    .addComponent(backBtn))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdB1ActionPerformed

    private void rdB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdB5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdB5ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
       GuideGUI g = new GuideGUI();
       g.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeedbackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeedbackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeedbackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeedbackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FeedbackGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> question1Cbx;
    private javax.swing.JLabel question1Lbl;
    private javax.swing.JLabel question2Lbl;
    private javax.swing.JLabel question3Lbl;
    private javax.swing.JLabel question4Lbl;
    private javax.swing.JComboBox<String> question5Cbx;
    private javax.swing.JLabel question5Lbl;
    private javax.swing.JRadioButton rdB1;
    private javax.swing.JRadioButton rdB2;
    private javax.swing.JRadioButton rdB3;
    private javax.swing.JRadioButton rdB4;
    private javax.swing.JRadioButton rdB5;
    private javax.swing.JRadioButton rdB6;
    private javax.swing.JRadioButton rdB7;
    private javax.swing.JRadioButton rdB8;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
