/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group.project;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Matty School
 */
public class VolunteerGUI extends javax.swing.JFrame {

    private ArrayList<Volunteer> volunteer;

    /**
     * Creates new form VolunteerGUI
     */
    public VolunteerGUI() {
        initComponents();
        pTimeLBL.setVisible(false);
        ftimeLBL.setVisible(false);
        pTimeTF.setVisible(false);
        fTimeTF.setVisible(false);
        salaryLBL.setVisible(false);
        salaryTF.setVisible(false);
        expTf.setVisible(false);
        expLbl.setVisible(false);
        volunteer = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        quizTitle = new javax.swing.JLabel();
        fNameLbl = new javax.swing.JLabel();
        fNameFld = new javax.swing.JTextField();
        lNameLbl = new javax.swing.JLabel();
        lNameFld = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        emailFld = new javax.swing.JTextField();
        pnumLbl = new javax.swing.JLabel();
        pnumFld = new javax.swing.JTextField();
        volunteerLbl = new javax.swing.JLabel();
        pTimeLBL = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        fullRDO = new javax.swing.JRadioButton();
        partRDO = new javax.swing.JRadioButton();
        viewBtn = new javax.swing.JButton();
        ftimeLBL = new javax.swing.JLabel();
        pTimeTF = new javax.swing.JTextField();
        fTimeTF = new javax.swing.JTextField();
        salaryTF = new javax.swing.JTextField();
        salaryLBL = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        expLbl = new javax.swing.JLabel();
        expTf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        quizTitle.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        quizTitle.setText("Sign Up");

        fNameLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        fNameLbl.setText("First Name:");

        fNameFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameFldActionPerformed(evt);
            }
        });

        lNameLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lNameLbl.setText("Last Name:");

        emailLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        emailLbl.setText("E-Mail:");

        pnumLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        pnumLbl.setText("Phone Number:");

        volunteerLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        volunteerLbl.setText("Volunteer Type:");

        pTimeLBL.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        pTimeLBL.setText("Part-Time Hours Per Week:");

        submitBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        submitBtn.setText("Submit Details");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(fullRDO);
        fullRDO.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        fullRDO.setText("Full-Time");
        fullRDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullRDOActionPerformed(evt);
            }
        });

        buttonGroup1.add(partRDO);
        partRDO.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        partRDO.setText("Part-Time");
        partRDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partRDOActionPerformed(evt);
            }
        });

        viewBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        viewBtn.setText("View Details");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        ftimeLBL.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        ftimeLBL.setText("Full-Time Hours Per Week:");

        salaryLBL.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        salaryLBL.setText("Allowance Needed (opitonal):");

        searchBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        searchBtn.setText("Search Details");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        expLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        expLbl.setText("Past Experience:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(pnumLbl))
                            .addComponent(emailLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailFld, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnumFld, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lNameLbl)
                            .addComponent(fNameLbl))
                        .addGap(58, 58, 58)
                        .addComponent(fNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(fullRDO, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(partRDO, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(salaryLBL)
                                        .addComponent(ftimeLBL)
                                        .addComponent(expLbl))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(submitBtn)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pTimeLBL)
                                .addGap(12, 12, 12)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pTimeTF)
                            .addComponent(fTimeTF)
                            .addComponent(salaryTF)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(viewBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addComponent(searchBtn)
                                .addGap(36, 36, 36))
                            .addComponent(expTf))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(volunteerLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(quizTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(quizTitle)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNameLbl)
                    .addComponent(fNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNameLbl)
                    .addComponent(lNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLbl)
                    .addComponent(emailFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnumLbl)
                    .addComponent(pnumFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(volunteerLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullRDO)
                    .addComponent(partRDO))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pTimeLBL)
                    .addComponent(pTimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftimeLBL)
                    .addComponent(fTimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salaryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salaryLBL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expLbl)
                    .addComponent(expTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitBtn)
                    .addComponent(backBtn)
                    .addComponent(viewBtn)
                    .addComponent(searchBtn))
                .addGap(83, 83, 83))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fNameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameFldActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        GuideGUI g = new GuideGUI();
        g.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void fullRDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullRDOActionPerformed
        // TODO add your handling code here:
        pTimeLBL.setVisible(false);
        expTf.setVisible(true);
        ftimeLBL.setVisible(true);
        expLbl.setVisible(true);
        pTimeTF.setVisible(false);
        fTimeTF.setVisible(true);
        salaryLBL.setVisible(true);
        salaryTF.setVisible(true);
    }//GEN-LAST:event_fullRDOActionPerformed

    private void partRDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partRDOActionPerformed
        // TODO add your handling code here:
        pTimeLBL.setVisible(true);
        expTf.setVisible(false);
        expLbl.setVisible(false);
        ftimeLBL.setVisible(false);
        pTimeTF.setVisible(true);
        fTimeTF.setVisible(false);
        salaryLBL.setVisible(false);
        salaryTF.setVisible(false);

    }//GEN-LAST:event_partRDOActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        if (fullRDO.isSelected()) {
            FullTime f = new FullTime();
            f.setfName(fNameFld.getText());
            f.setlName(lNameFld.getText());
            f.setEmail(emailFld.getText());
            f.setExperience(expTf.getText());
            f.setpNumber(Integer.parseInt(pnumFld.getText()));
            f.setfTime(fTimeTF.getText());
            int min = 25; // setting the minimum value for full time hours so it doesn't overlap with part time
            int fullTimeHours = Integer.parseInt(pTimeTF.getText());
            if (fullTimeHours < min) {
                JOptionPane.showMessageDialog(null, "Full-time hours cannot be below " + min);
                return;
            }
            f.setWeeklySalary(Integer.parseInt(salaryTF.getText()));
            volunteer.add(f);
        } else if (partRDO.isSelected()) {
            PartTime p = new PartTime();
            p.setfName(fNameFld.getText());
            p.setlName(lNameFld.getText());
            p.setEmail(emailFld.getText());
            p.setpNumber(Integer.parseInt(pnumFld.getText()));
            p.setpTime(fTimeTF.getText());
            int max = 25; // setting the maximum hours for part time so that the hours don't overlap with each other 
            int partTimeHours = Integer.parseInt(pTimeTF.getText());
            if (partTimeHours > max) {
                JOptionPane.showMessageDialog(null, "Part-time hours cannot exceed " + max);
                return;
            }
            volunteer.add(p);
        }


    }//GEN-LAST:event_submitBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here: 
        for (Volunteer v : volunteer) {
            JOptionPane.showMessageDialog(null, v.getDetails());
        }
    }//GEN-LAST:event_viewBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        if (volunteer.isEmpty()) {
            JOptionPane.showMessageDialog(null, "sorry there are no volunteers to delete");
        } else {
            String searchTerm = JOptionPane.showInputDialog(null, "Please enter a name to search");
            for (Volunteer v : volunteer) {
                if (v.getfName().equalsIgnoreCase(searchTerm)) {
                    JOptionPane.showMessageDialog(null, v.getDetails());
                }
            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VolunteerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VolunteerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VolunteerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VolunteerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VolunteerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField emailFld;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JLabel expLbl;
    private javax.swing.JTextField expTf;
    private javax.swing.JTextField fNameFld;
    private javax.swing.JLabel fNameLbl;
    private javax.swing.JTextField fTimeTF;
    private javax.swing.JLabel ftimeLBL;
    private javax.swing.JRadioButton fullRDO;
    private javax.swing.JTextField lNameFld;
    private javax.swing.JLabel lNameLbl;
    private javax.swing.JLabel pTimeLBL;
    private javax.swing.JTextField pTimeTF;
    private javax.swing.JRadioButton partRDO;
    private javax.swing.JTextField pnumFld;
    private javax.swing.JLabel pnumLbl;
    private javax.swing.JLabel quizTitle;
    private javax.swing.JLabel salaryLBL;
    private javax.swing.JTextField salaryTF;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton submitBtn;
    private javax.swing.JButton viewBtn;
    private javax.swing.JLabel volunteerLbl;
    // End of variables declaration//GEN-END:variables
}
