/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group.project;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Matty School
 */
public class VolunteerGUI extends javax.swing.JFrame {

    /**
     * Creates new form VolunteerGUI
     */
    public VolunteerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quizTitle = new javax.swing.JLabel();
        fNameLbl = new javax.swing.JLabel();
        fNameFld = new javax.swing.JTextField();
        lNameLbl = new javax.swing.JLabel();
        lNameFld = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        emailFld = new javax.swing.JTextField();
        pnumLbl = new javax.swing.JLabel();
        pnumFld = new javax.swing.JTextField();
        volunteerLbl = new javax.swing.JLabel();
        volunteerCbx = new javax.swing.JComboBox<>();
        hoursLbl = new javax.swing.JLabel();
        hoursCbx = new javax.swing.JComboBox<>();
        submitBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        quizTitle.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        quizTitle.setText("Sign Up");

        fNameLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        fNameLbl.setText("First Name:");

        fNameFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameFldActionPerformed(evt);
            }
        });

        lNameLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lNameLbl.setText("Last Name:");

        emailLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        emailLbl.setText("E-Mail:");

        pnumLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        pnumLbl.setText("Phone Number:");

        volunteerLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        volunteerLbl.setText("Volunteer Type:");

        volunteerCbx.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        volunteerCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select a choice", "Full-Time", "Part-Time" }));

        hoursLbl.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        hoursLbl.setText("Hours Per Week:");

        hoursCbx.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        hoursCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select a choice", "3", "3.5", "4", "4.5", "5", "5.5", "6", "6.5", "7", "7.5", "8" }));

        submitBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        submitBtn.setText("Submit Details");

        backBtn.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fNameLbl)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lNameLbl)
                                    .addComponent(emailLbl)
                                    .addComponent(pnumLbl)
                                    .addComponent(volunteerLbl)
                                    .addComponent(hoursLbl))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pnumFld, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(emailFld, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(hoursCbx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(volunteerCbx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(quizTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(submitBtn)
                        .addGap(62, 62, 62)
                        .addComponent(backBtn)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(quizTitle)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fNameLbl)
                            .addComponent(fNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lNameLbl)
                            .addComponent(lNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLbl)
                            .addComponent(emailFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pnumLbl)
                            .addComponent(pnumFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(volunteerLbl)
                            .addComponent(volunteerCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hoursLbl)
                            .addComponent(hoursCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(187, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submitBtn)
                            .addComponent(backBtn))
                        .addGap(122, 122, 122))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fNameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameFldActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        GuideGUI g = new GuideGUI();
        g.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VolunteerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VolunteerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VolunteerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VolunteerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VolunteerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField emailFld;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField fNameFld;
    private javax.swing.JLabel fNameLbl;
    private javax.swing.JComboBox<String> hoursCbx;
    private javax.swing.JLabel hoursLbl;
    private javax.swing.JTextField lNameFld;
    private javax.swing.JLabel lNameLbl;
    private javax.swing.JTextField pnumFld;
    private javax.swing.JLabel pnumLbl;
    private javax.swing.JLabel quizTitle;
    private javax.swing.JButton submitBtn;
    private javax.swing.JComboBox<String> volunteerCbx;
    private javax.swing.JLabel volunteerLbl;
    // End of variables declaration//GEN-END:variables
}
